version: "2.2"

services:
  nginx-http-flv:
    image: 'nginx-http-flv:latest'
    container_name: 'nginx-http-flv'
    restart: always
    ulimits:
      sigpending: 120465
      nproc: 120465
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./nginx:/etc/nginx
    ports:
      # 如果遇到浏览器同源问题，可用使用一对多映射端口
      - '8080:8080'
      - '8081:8080'
      - '8082:8080'
      - '8083:8080'
      - '1935:1935'
